

server:
  port: 80



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:8761/eureka/,http://eureka02:8762/eureka/
spring:
  application:
    name: cloud-consumer-order

