server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:8761/eureka/,http://eureka02:8762/eureka/
spring:
  application:
    name: cloud-consumer-order
logging:
  level:
    top.freshgeek.springcloud.order.feign.PaymentService: debug

ribbon:
  #请求处理的超时时间
  ReadTimeout: 5000

# feign 的hystrix 支持开启 默认是关闭
feign:
  hystrix:
    enabled: true
