server:
  port: 80
spring:
  cloud:
    nacos:
      discovery:
        server-addr: local:8848
    sentinel:
      transport:
        # 刚才的sentinel 控制台地址
        dashboard: local:8858
        # 默认端口  假如被占用从8719开始+1扫描直到直到未被占用的端口
        port: 8719
  application:
    name: cloud-consumer-order
    # zipkin+sleuth 请求链路监控
  zipkin:
    base-url: http://local:9411
  sleuth:
    sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1
logging:
  level:
    top.freshgeek.springcloud.order.feign.PaymentService: debug
ribbon:
  #请求处理的超时时间
  ReadTimeout: 5000
feign:
  sentinel:
    enabled: true


