server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  #### consul 注册中心  注解与zookeeper 一致
  cloud:
    consul:
      host: 192.168.203.102
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 心跳检测默认是关，需要打开
        heartbeat:
          enabled: true