

server:
  port: 80



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:8761/eureka/,http://eureka02:8762/eureka/
spring:
  application:
    name: cloud-consumer-order

  # 单个就配置单独一个即可
  cloud:
    zookeeper:
      connect-string: localhost:2181,localhost:2182,localhost:2183
