server:
  port: 8761
eureka:
  instance:
    hostname: eureka01
  client:
    # 不注册自己
    register-with-eureka: true
    # 维护 不检索
    fetch-registry: true
    service-url:
      defaultZone: http://eureka02:8762/eureka/
  server:
    # 默认自我保护，如果开启可能出现，请求不存在的实例
    enable-self-preservation: true
    # 清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 10
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: eureka-server
logging:
  level:
    com:
      netflix:
        eureka:
          registry: warn