server:
  port: 2003

spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: account-service-group
logging:
  level:
    io:
      seata: info

management:
  endpoints:
    web:
      exposure:
        include: '*'