server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://data.keepon.site:3306/springcloud-seata?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: springcloud
    password: springcloud
    # 这里用了jpa 省得写dao了
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: storage_tx_group
    nacos:
      discovery:
        server-addr: nacos:8848

logging:
  level:
    io:
      seata: info
