server:
  port: 8005

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://data.keepon.site:3306/springcloud-payment?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: springcloud
    password: springcloud
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#### consul 注册中心  注解与zookeeper 一致
  cloud:
    consul:
      host: 192.168.35.3
      port: 8500
      discovery:
        service-name: ${spring.application.name}
debug: true
