server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://data.keepon.site:3306/springcloud-payment?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: springcloud
    password: springcloud
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # 单个就配置单独一个即可
  cloud:
    zookeeper:
      connect-string: 192.168.203.102:2181 , 192.168.203.102:2182 , 192.168.203.102:2183
